# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(998, 731)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.ironman = QtWidgets.QLabel(Form)
        self.ironman.setGeometry(QtCore.QRect(620, 0, 381, 721))
        self.ironman.setText("")
        self.ironman.setPixmap(QtGui.QPixmap("../UI/ironman.png"))
        self.ironman.setScaledContents(True)
        self.ironman.setObjectName("ironman")
        self.camera = QtWidgets.QLabel(Form)
        self.camera.setGeometry(QtCore.QRect(6, 162, 611, 481))
        self.camera.setText("")
        self.camera.setPixmap(QtGui.QPixmap("../UI/fram1.png"))
        self.camera.setScaledContents(True)
        self.camera.setObjectName("camera")
        self.login = QtWidgets.QLabel(Form)
        self.login.setGeometry(QtCore.QRect(0, 640, 181, 121))
        self.login.setStyleSheet("background-color: transparent;")
        self.login.setText("")
        self.login.setPixmap(QtGui.QPixmap("../UI/login.png"))
        self.login.setScaledContents(True)
        self.login.setObjectName("login")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(270, 630, 181, 121))
        self.label_5.setStyleSheet("background-color: transparent;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../UI/exit.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.loginbutton = QtWidgets.QPushButton(Form)
        self.loginbutton.setGeometry(QtCore.QRect(10, 660, 151, 71))
        self.loginbutton.setStyleSheet("background-color: transparent;")
        self.loginbutton.setText("")
        self.loginbutton.setObjectName("loginbutton")
        self.exitbutton = QtWidgets.QPushButton(Form)
        self.exitbutton.setGeometry(QtCore.QRect(280, 650, 151, 71))
        self.exitbutton.setStyleSheet("background-color: transparent;")
        self.exitbutton.setText("")
        self.exitbutton.setObjectName("exitbutton")
        self.face = QtWidgets.QLabel(Form)
        self.face.setGeometry(QtCore.QRect(10, 10, 601, 151))
        self.face.setText("")
        self.face.setPixmap(QtGui.QPixmap("../UI/face.png"))
        self.face.setScaledContents(True)
        self.face.setObjectName("face")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
